### ISSUE TITLE
What is the second paramter in setSpeed for?

### ISSUE THREAD

**Issue by Andry60351** [ibrahimsn98/speedometer#2]
Hi there!

I was gonna use your library it seemed really great, but I was curious, what is the second parameter in "setSpeed()" used for?

I'm asking because I tried to use 1000L and 1L and there wasn't any difference?

I was also wondering if you were planning to maintain this library in the future?

Many thanks!

**Comment by ibrahimsn98** [comment]
Hello,

As I described in the readme, second parameter is for speed changing animation duration.
`speedometer.setSpeed(95, 1000L) // speed: Int, duration: Long`

I'm reviewing pull requests, issues. So, it's open to contribute. Thanks :)

**Comment by Andry60351** [comment]
Ah, that makes sense, I thought that "duration" was how much time the speed was displayed for, thanks for clarifying!
